### ISSUE TITLE
Cannot run Program under Windows

### ISSUE THREAD

**Issue by stschroe** [dropbox/mypy-PyCharm-plugin#10]
A Plugin Exeption was raised after hitting the Run button:
Cannot run program "/bin/bash" (in directory "...my project directory..."): \dev\null (The system cannot find the specified path.)

My System:
Windows 7
PyCharm Professional 2018.1
Python 3.6 (Anaconda)

**Comment by ilevkivskyi** [comment]
Unfortunately, this is a known limitation. Also mypy daemon itself doesn't work on Windows yet. Windows support is definitely planned, but it is hard to give any estimates.

**Comment by Cito** [comment]
Would be nice if this could be solved. One problem is that MypyRunner.java has hardcoded `/bin/bash`  and `/dev/null` paths which do not exist under Windows. The mypy daemon issue is here: https://github.com/python/mypy/issues/5019

**Comment by Ricyteach** [comment]
another pycharm on windows user looking forward to this enhancement.

**Comment by chandimsett** [comment]
Please add Windows support as we are looking forward for static-typing checking in Pycharm IDE in Windows OS.
