### ISSUE TITLE
MyPy plugin doesn't work when the Python interpreter (and MyPy installation) are in a dockerized Python

### ISSUE THREAD

**Issue by salimfadhley** [dropbox/mypy-PyCharm-plugin#25]
The plugin works fine if we use base system python or a virtual environment, however, if the Project's interpreter is running from Docker or a docker-compose configuration, the plugin doesn't seem to run.

I have a Python interpreter running from a Docker-Compose image. The image contains Python 3.6 and the MyPy library.

When you try to run the plugin you get a bubble:

```
Mypy Plugin
No Pythion interpreter is configured for the project.
Configure Python interpreter
```

If you click on "Configure Python Interpreter" it takes you to the Project Interpreter settings, however, there already is a Python interpreter for the project.

**Comment by MrSaints** [comment]
```
java.lang.Throwable: Mypy path detect process.exitValue: 1
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.detectSystemMypyPath(MypyRunner.java:216)
```

<img width="1430" alt="screen shot 2018-12-12 at 10 12 14" src="https://user-images.githubusercontent.com/68859/49862632-7c0fea00-fdf6-11e8-87bd-f7c5d5492a87.png">
<img width="346" alt="screen shot 2018-12-12 at 10 12 24" src="https://user-images.githubusercontent.com/68859/49862633-7c0fea00-fdf6-11e8-8099-bdfc7525fc3f.png">

**Comment by ilevkivskyi** [comment]
Looking at the screenshots I got in an e-mail (I have no idea why the comment is not here anymore, was it deleted?) this is not our plugin.

**Comment by MrSaints** [comment]
Hey @ilevkivskyi, yep, I deleted it after I found out, it was probably the wrong plugin. It is the one installed from the marketplace, not manually. After installing this one, I got it working by modifying the command used, to use Docker instead. Looks like it works.

**Comment by aguestuser** [comment]
@MrSaints having a similar issue: how did you "modify.. the command used"?

**Comment by aguestuser** [comment]
answered my own question: you right-click anywhere in the mypy terminal module and click "Configure plugin..." from the contextual dropdown
