### ISSUE TITLE
Does not recognize a stubs package (numpy-stubs)

### ISSUE THREAD

**Issue by ilirium** [dropbox/mypy-PyCharm-plugin#40]
The plugin does not recognize a stubs package and it raises the "No library stub file for module" error, however `mypy` rightly works.

I installed the stubs package from https://github.com/numpy/numpy-stubs:
1) `$ git clone https://github.com/numpy/numpy-stubs`
2) `$ pip install -e numpy-stubs`

3) Then I tried to check the next script:
```python
import numpy as np

array = np.array([10, 20, 30])

new_array = np.array()
```

4) Error:
```
annotations/num_py/simple.py:1: error: No library stub file for module 'numpy'
annotations/num_py/simple.py:1: note: (Stub files are from https://github.com/python/typeshed)
```

5) Use `mypy` to check:
`$ mypy --follow-imports=error simple.py`

6) Output:
`simple.py:5: error: Too few arguments for "array"`

My environment:
* Anaconda v4.7.12
* Python v3.7.4
* Mypy v0.720
* PyCharm v2019.2.3 (Pro)
* The plugin from the 27b6712 commit
* Numpy v1.17.2
* Numpy-stubs from the numpy/numpy-stubs@be9a47933de1b89e482b05b16c0a493da2dcb14a commit

**Comment by ilevkivskyi** [comment]
The plugin uses `dmypy run`, do you see no errors when you run `dmypy run --follow-imports=error simple.py` on command line? If no, then maybe you have some tricky virtual environment situation? I remember I had problems with editable installations (the `-e` flag) so I would not recommend using it unless you really need it. If you do need it, you can try playing with adding something to `PATH suffix` (right click in plugin window -> Configure plugin...)

**Comment by ilirium** [comment]
Oh, sorry, it is just the "try to reboot your computer" error :) I've restarted the editor and the error was gone.
