### ISSUE TITLE
Running the plugin creates a file .dmpy.json on the root folder

### ISSUE THREAD

**Issue by rommguy** [dropbox/mypy-PyCharm-plugin#43]
Every time I run the plugin, I see a file is created ".dmypy.json"
If it is needed during the run I think It should be cleaned when the run is over, to avoid changes to the source control even though nothing changed in the source. 

Running mypy doesn't create this file.

**Comment by rommguy** [comment]
Just read about it in the Mypy docs
I understand the plugin uses the experimental mypy daemon
I'll just add it to .gitignore

**Comment by ilevkivskyi** [comment]
> I understand the plugin uses the experimental mypy daemon

Yes, ecxept the daemon is de facto not experimental anymore (it is around for a year and half now). We use it because it gives _much_ faster response.
