### ISSUE TITLE
'dmypy' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by mozesa** [dropbox/mypy-PyCharm-plugin#47]
**Hello**,

I would like to ask for your kind support.

My problem is that:
`'dmypy' is not recognized as an internal or external command, operable program or batch file.`

I have Windows10 and Python 3.8, PyCharm with mypy-PyCharm-plugin installed from Marketplace.

![dmypy](https://user-images.githubusercontent.com/49973426/69410401-42847600-0d0b-11ea-93ab-44677e65dd03.png)

Thanks for your help in advance.

**Comment by ilevkivskyi** [comment]
I think you just need to configure your `PATH suffix` as explained in [README](https://github.com/dropbox/mypy-PyCharm-plugin#configuration)

**Comment by mozesa** [comment]
I have done but it didn't help.

Interesting because it works from PyCharm local Terminal.
`(venv) C:\Users\mozesa\PycharmProjects\V316-Production-Line>mypy C:\Users\mozesa\PycharmProjects\V316-Production-Line\v316_production_line\codereader\handheld.py`

![dmypy2](https://user-images.githubusercontent.com/49973426/69411487-5af59000-0d0d-11ea-80b8-85908e8768dd.png)

**Comment by ilevkivskyi** [comment]
That's wrong path, as mentioned there, it should be the `Scripts` directory of your project virtual environment, in your case probably `C:\...\V316-Production-Line\venv\Scripts`.

**Comment by mozesa** [comment]
Ohh, Thanks. Now it works like a charm.
