### ISSUE TITLE
support running mypy in dockerized environment

### ISSUE THREAD

**Issue by yoav-orca** [dropbox/mypy-PyCharm-plugin#54]
Hi,
I'm trying to use the plugin with PyCharm 2020.1.1 with an interpreter within docker but I'm unable to specify the path within the container for dmypy. 
It seems that the plugin only supports local interpreters.
I think it would be a great enhancement for the plugin

**Comment by ilevkivskyi** [comment]
I think this is essentially a duplicate of https://github.com/dropbox/mypy-PyCharm-plugin/issues/48. I will add a comment there that this also affects docker.
