### ISSUE TITLE
Installation Instructions?

### ISSUE THREAD

**Issue by vinitkumar** [dropbox/mypy-PyCharm-plugin#6]
Hi, wanted to use it. Can't find it in Pycharm plugins or repositories. Could you please add installation? I also downloaded the repo and trying to import setting mypy-plugin.jar, It didn't work. Please let me know if I am doing something wrong.

Thanks :)

**Comment by ilevkivskyi** [comment]
Yes, sorry, I will add installation steps. It should be quite simple:
1. Download `mypy-plugin/mypy-plugin.jar`
2. In PyCharm go to Preferences -> Plugins -> Install plugins from disc -> Select this file -> Restart PyCharm when prompted.
3. After restart you should find the plugin in View -> Tool windows -> Mypy terminal

Does this work for you?

**Comment by ilevkivskyi** [comment]
Just a note: The plugin requires mypy to be already installed.

**Comment by vinitkumar** [comment]
@ilevkivskyi Thanks for your response.

**Comment by vinitkumar** [comment]
Alright, I am able to install it but not able to make it work properly. Getting `/bin/bash: dmypy: command not found`

Which is strange since I have mypy installed.

![screenshot 2018-05-31 at 2 10 32 am](https://user-images.githubusercontent.com/537678/40746484-2eb4d4ae-6478-11e8-8f26-417ee5620879.png)
![screenshot 2018-05-31 at 2 11 08 am](https://user-images.githubusercontent.com/537678/40746486-2eeafb2e-6478-11e8-9213-39f13a217067.png)

Sorry for bothering with these small issues. Just excited to get it to work.

**Comment by ilevkivskyi** [comment]
This means you need to configure the `PATH` prefix. Right click on mypy terminal -> Configure plugin. There you need to enter the place where you installed mypy. It looks like you are using virtualenv, this means mypy is installed there, so you need to enter `~/.virtualenvs/celery/bin` (like in your Python version on the screenshot above, but without Python at the end). Does this work now?

**Comment by vinitkumar** [comment]
Indeed. That was the issue. Thanks for your help. Really appreciate it. 👍
