### ISSUE TITLE
Distribute the plugin via JetBrains plugins repository

### ISSUE THREAD

**Issue by vlasovskikh** [dropbox/mypy-PyCharm-plugin#7]
It's more convenient for PyCharm / IntelliJ users to get their plugins as in-app updates via the [JetBrains repository](https://plugins.jetbrains.com). Please consider distributing the plugin via this channel instead of a manual download + install via a file.

**Comment by ilevkivskyi** [comment]
Thanks for suggestion!

I was already thinking about this, but I first need to figure out how to avoid conflicts with our internal version of this plugin. It is identical to public one, but is preconfigured with our internal PATHs and mypy runner scripts.

**Comment by vlasovskikh** [comment]
@ilevkivskyi I could recommend storing your company configuration in the settings of the projects you're working on. Either as mypy config files or as per-project settings represented via the settings UI of PyCharm that can be stored and shared in the project files inside the .idea/ folder.

**Comment by quicknir** [comment]
Any update on this? Also, if added to jetbrains repositories, could it be added not just for pycharm, but also for other IDEs that support python through a plugin? (e.g. CLion, Intellij)

**Comment by vlasovskikh** [comment]
@quicknir Update: @ilevkivskyi and I have been fixing issues that prevent it to be published at the plugins repository. It's still in progress, there are a couple of bugs and organizational issues left unresolved.

**Comment by quicknir** [comment]
Thanks, good to hear! Looking forward.

**Comment by lorencarvalho** [comment]
Hi! Any updates on this issue? Would love to see this plugin in the marketplace :)

**Comment by revolutionisme** [comment]
There's this plugin which is available in the plugins repository:
https://github.com/leinardi/mypy-pycharm

How well does it compare to this one which we can make and put from outside, anyone has any insights?

**Comment by ilevkivskyi** [comment]
FWIW, if everything goes well we are going to publish the plugin on JetBrains repository next week.

**Comment by revolutionisme** [comment]
That sounds great, thanks a lot for the update.

**Comment by rommguy** [comment]
@revolutionisme mypy-pycharm works well, but has no solution for remote interpreter. If you only run locally it will be good enough.

**Comment by rommguy** [comment]
Thanks @ilevkivskyi! 
This is an awesome plugin.
Can you please keep this issue open until JetBrains approve the plugin? It is still not available

**Comment by ilevkivskyi** [comment]
> Can you please keep this issue open until JetBrains approve the plugin?

No, we close issues for which there are no action items.

**Comment by ilevkivskyi** [comment]
A little update: the plugin was approved and is available for direct install, see https://plugins.jetbrains.com/plugin/13348-mypy-official-
