### ISSUE TITLE
/bin/bash: dmypy: command not found

### ISSUE THREAD

**Issue by fniessink** [dropbox/mypy-PyCharm-plugin#8]
This is with PyCharm 2018.1.3 CE on macOS High Sierra 10.13.4, Python 3.6.1, mypy 0.600.

In a regular bash:
```console
$ which mypy
/Library/Frameworks/Python.framework/Versions/3.6/bin/mypy
$ which dmypy
/Library/Frameworks/Python.framework/Versions/3.6/bin/dmypy
```

So everything seems to be fine, except that the plugin can't find dmypy. Could it be that the plugin is using the wrong Python version (Macs also have a Python 2.7 version)?

**Comment by ilevkivskyi** [comment]
Plugin cannot find your install because it doesn't have full environment. I think the simplest solution is right click in plugin window -> Configure window -> set PATH suffix to the bin directory where you installed mypy. Does this work for you?

**Comment by ilevkivskyi** [comment]
(Also I think I will add configuration steps in README, since this problem already appeared few times.)

**Comment by fniessink** [comment]
@ilevkivskyi Yes, that helps. Got it working now. Thanks!

**Comment by codenamesubho** [comment]
@fniessink @srgkm I am using Pycharm 2019.2 build, can you mention how to find configure window? Is plugin window the window with list of plugins installed/marketplace?

**Comment by ilevkivskyi** [comment]
@codenamesubho The window of the plugin itself (i.e. what appears at the lower part of PyCharm window on the screenshot in README).
