### ISSUE TITLE
hdpi support

### ISSUE THREAD

**Issue by gaborbernat** [dropbox/mypy-PyCharm-plugin#9]
On a 4k 15" the font is all messed up (really small).

![image](https://user-images.githubusercontent.com/690238/40776571-07ada71e-64c3-11e8-960d-6a43a6db4382.png)

PY-182.2574.7, JRE 1.8.0_152-release-1226-b7x64 JetBrains s.r.o, OS Linux(amd64) v4.16.11-1-ARCH unknown, screens 3840x2160

@ilevkivskyi

**Comment by ilevkivskyi** [comment]
Oh yes, this looks horrible, thanks for adding the screenshot!

**Comment by Gee5ive** [comment]
any updates on this issue ? the plugin is almost unusable on my system as well.


![deepinscreenshot_sun-awt-x11-xframepeer_20180824063739](https://user-images.githubusercontent.com/42525743/44611017-13601b80-a7cd-11e8-897e-4573bc0ecd4f.png)

**Comment by ilevkivskyi** [comment]
> any updates on this issue?

Unfortunately I didn't have time to work on this yet. Also, as usual, PRs are very welcome :-)

**Comment by ilevkivskyi** [comment]
@gaborbernat Could you please attach the PyCharm log? It is in Help -> Show Log in ... This will be very helpful to diagnose this.

**Comment by gaborbernat** [comment]
@ilevkivskyi I no longer can replicate this on my system.

**Comment by insanitybit** [comment]
This is happening on my intellij with the plugin installed. The text is extremely small.

Ubuntu 18.04
Screen resolution: 3840x2160 pixels (1016x572 millimeters)

**Comment by ilevkivskyi** [comment]
> This is happening on my intellij with the plugin installed.

Hm, interesting. @msullivan is there any chance you can try reproducing this? IIRC you have Ubuntu 18.04 and a high resolution display.

**Comment by ilevkivskyi** [comment]
@insanitybit Btw, what is the IntelliJ/PyCharm version you are using? We recommend 2019+

**Comment by insanitybit** [comment]
I'm on 2019.2, Intellij Ultimate, and I've only just installed the plugin today (and restarted).

**Comment by insanitybit** [comment]
![Screenshot from 2019-11-27 10-13-00](https://user-images.githubusercontent.com/4956357/69750324-58c27580-1101-11ea-88c1-f8c307214727.png)

Here's a screenshot. A bit hard to tell from it just how small since it's blown up, but uh, imagine that's really really tiny.
